services:
  web:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION}
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS
    env_file:
      - 1panel.env
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
  chrome:
    container_name: ${CONTAINER_NAME}-chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    env_file:
      - 1panel.env
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
  meilisearch:
    container_name: ${CONTAINER_NAME}-meilisearch
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    env_file:
      - 1panel.env
    volumes:
      - ./meili_data:/meili_data
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
